namespace NuxtIdentity.Core.Abstractions;

/// <summary>
/// Notifies a user about account-related events.
/// </summary>
/// <typeparam name="TUser">The type of user.</typeparam>
/// <remarks>
/// The consumer implements this interface to deliver notifications however they
/// choose — email, SMS, push notification, etc. The consumer is responsible for
/// composing URLs, message body, localization, and all formatting. The library
/// provides only the user object and the raw codes/tokens.
///
/// If no implementation is registered, endpoints that require notification still
/// succeed but log a warning that no notifier is configured.
///
/// The <see cref="SendEmailConfirmationAsync"/> method is included to support a
/// future email confirmation feature without requiring an interface refactor.
/// </remarks>
public interface IUserNotifier<TUser> where TUser : class
{
    /// <summary>
    /// Sends the password reset code to the specified user.
    /// </summary>
    /// <param name="user">The user requesting the password reset.</param>
    /// <param name="resetCode">The reset code generated by ASP.NET Identity.</param>
    Task SendResetCodeAsync(TUser user, string resetCode);

    /// <summary>
    /// Sends the email confirmation code to the specified user.
    /// </summary>
    /// <param name="user">The user whose email needs confirmation.</param>
    /// <param name="confirmationCode">The confirmation code generated by ASP.NET Identity.</param>
    Task SendEmailConfirmationAsync(TUser user, string confirmationCode);
}
