namespace NuxtIdentity.Core.Abstractions;

using NuxtIdentity.Core.Models;

/// <summary>
/// Notifies a user about account-related events.
/// </summary>
/// <remarks>
/// The consumer implements this interface to deliver notifications however they
/// choose — email, SMS, push notification, etc. The consumer is responsible for
/// composing URLs, message body, localization, and all formatting. The library
/// provides only a transport-neutral recipient payload and the raw codes/tokens.
///
/// If no implementation is registered, endpoints that require notification
/// (e.g. forgot-password) will throw a
/// <see cref="NuxtIdentity.Core.Exceptions.NuxtIdentityConfigurationException"/>
/// to signal the misconfiguration.
///
/// The <see cref="SendEmailConfirmationAsync"/> method is included to support a
/// future email confirmation feature without requiring an interface refactor.
/// </remarks>
public interface IUserNotifier
{
    /// <summary>
    /// Sends the password reset code to the specified user.
    /// </summary>
    /// <param name="recipient">The recipient requesting the password reset.</param>
    /// <param name="resetCode">The reset code generated by ASP.NET Identity.</param>
    Task SendResetCodeAsync(NotificationRecipient recipient, string resetCode);

    /// <summary>
    /// Sends the email confirmation code to the specified user.
    /// </summary>
    /// <param name="recipient">The recipient whose email needs confirmation.</param>
    /// <param name="confirmationCode">The confirmation code generated by ASP.NET Identity.</param>
    Task SendEmailConfirmationAsync(NotificationRecipient recipient, string confirmationCode);
}
