<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>NuxtIdentity.EntityFrameworkCore</PackageId>
    <Description>Entity Framework Core implementation of refresh token storage for Nuxt Identity</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <ProjectReference Include="..\Core\NuxtIdentity.Core.csproj" />
    <ProjectReference Include="..\AspNetCore\NuxtIdentity.AspNetCore.csproj" />
  </ItemGroup>

</Project>
